

FIND_PATH(ANTTWEAKBAR_INCLUDE_DIR AntTweakBar.h
  HINTS
  $ENV{ANTTWEAKBAR_HOME}
  PATH_SUFFIXES include
  PATHS
  $ENV{ANTTWEAKBAR_HOME}/include
  ~/Library/Frameworks
  /Library/Frameworks
  /opt
)

FIND_LIBRARY(ANTTWEAKBAR_LIBRARY
  NAMES AntTweakBar
  HINTS
  $ENV{ANTTWEAKBAR_HOME}
  PATH_SUFFIXES lib
  PATHS
  /sw
  /opt/local
  /opt/csw
  /opt
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(AntTweakBar REQUIRED_VARS ANTTWEAKBAR_LIBRARY ANTTWEAKBAR_INCLUDE_DIR)
